# Site settings
title: Tran Le Cuong
email: cuongtl92@gmail.com
description: >-
  Technical Director at KiotViet with expertise in software architecture,
  leadership, and full-stack development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lecuong.me" # the base hostname & protocol for your site
github_username: # your GitHub username
linkedin_username: # your LinkedIn username

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variables
full_name: Tran Le Cuong
job_title: Technical Director
company: KiotViet
phone: 0389.464.693
dob: 1992-09-19
location: Hanoi, Vietnam

# Jekyll Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Collections
collections:
  sections:
    output: false